version: '2'
services:
  qcodebase-app:
    image: qcodebase
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://qcodebase-postgresql:5432/qcodebase
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://qcodebase-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://qcodebase-elasticsearch:9200
    ports:
      - 8080:8080
  qcodebase-postgresql:
    extends:
      file: postgresql.yml
      service: qcodebase-postgresql
  qcodebase-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: qcodebase-elasticsearch
