version: '2'
services:
  qcodebase-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/qcodebase/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=qcodebase
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
